### ISSUE TITLE
[Suggestion] Start Crop IDs at 50

### ISSUE THREAD

**Issue by JPANv2** [spacechase0/JsonAssets#34]
The current crop ID system starts at 100, at the y = 1600 position of the crop image. Vanilla image ends at 672, leaving almost 60 possible crops to fill. This wouldn't be a problem but in the game I'm playing I ended up having nearly 30 JsonAssets loaded crops with no image because the limit (y=4096) was reached.

Starting at 50 would solve this temporarily, as id= 50 means crops would be placed starting at y=800, and provide space for 50 more crops, while keeping the start id at a relatively normal value.

Another possible solution is to extend the sprite sheet sideways, meaning id = 256 would be placed at x=256, y= 0, and id = 512 at x=512, etc.

**Comment by captncraig** [comment]
Couldn't you also increase the max height. 4096 looks rather arbitrary. It could possibly be dynamically calculated as well?

**Comment by JPANv2** [comment]
4096x4096 sized textures are the maximum possible size for a texture in XNA. I found that out when I tried  editing this code expanding the texture size further than 4096 to avoid changing the IDs and the crop rectangle formula.

**Comment by spacechase0** [comment]
No longer necessary with SpaceCore's spritesheet extension.
