### ISSUE TITLE
Missing default (English) name at GameMenu/Crafting page for non-English locale

### ISSUE THREAD

**Issue by qqkookie** [spacechase0/JsonAssets#37]
The large craftable item is "Daisy Pot" from the "JsonAssets - Farmer to Florist" mod. It has English name and description,  but does not have localized name and description.  So for player of non-English locale, the name and description of the item should be displayed in default English. But the name is displayed as "null"

 When player try to purchase the recipe of the item at Robin's Carpenter Shop, the name and description are  displayed correctly. i.e it shows English name and description. But after purchasing the recipe and then open the GameMenu/Crafting page, the hover information box displays name of the crafting item  as "null", not English name.  The description is displayed correctly in English. 

Adding localized name to the "big-craftable.json" file ( with "NameLocalization" tag) does not fix the problem. Crafted item itself has correct default English or  localized name. So the root of the problem is not localization.  I guess that the localized name should be added to object database, too.

![Large-craftable](https://user-images.githubusercontent.com/39845532/63448968-10e4e000-c47a-11e9-9114-729b89e06fd6.jpg)

**Comment by spacechase0** [comment]
Fixed... recently-ish
