### ISSUE TITLE
Unable to use assets from other JA Content Packs

### ISSUE THREAD

**Issue by paradigmnomad** [spacechase0/JsonAssets#8]
After moving pre-existing content packs out of `ContentPacks` to `/Mods` they are no longer able to use items from other content packs.

Ex. `Gooseberry Pie` from More Recipes requires `Gooseberry` from Fruits & Veggies.

[Affected Content Packs.zip](https://github.com/spacechase0/JsonAssets/files/1768118/Affected.Content.Packs.zip)
[JsonAssets.zip](https://github.com/spacechase0/JsonAssets/files/1768123/JsonAssets.zip)

This issue might be resolved but due to another issue I cannot get SMAPI to replicate it. Further testing is required.

**Comment by spacechase0** [comment]
I'm told this is not still an issue. Will re-open if found again later.
